# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0002_auto_20151223_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
