# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0004_game_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='password',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
