# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0005_auto_20151227_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
