# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0006_auto_20151227_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='players',
            field=models.ManyToManyField(to='virtual_league.Player'),
        ),
    ]
