# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0007_auto_20151229_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='face',
            field=models.ImageField(default=None, upload_to=b''),
        ),
    ]
