# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0012_auto_20151230_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='face',
        ),
    ]
