# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_league', '0016_auto_20151230_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='face',
            field=models.ImageField(default='virtual_league/static/images/faces/default.png', upload_to='virtual_league/static/images/faces'),
        ),
    ]
